apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: erlanggajuni45/ticketing-app/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        target: dev
      sync:
        manual:
          - src: '**/*.go'
            dest: .